import { type NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.css";

import Chart from "../components/BasicChart";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const now = new Date().getTime();
  const nowMinus = new Date(now - 5 * 60 * 1000);
  const date = nowMinus.toISOString().split("T")[0];
  const closestQuarter = (
    (Math.round(nowMinus.getMinutes() / 15) * 15) %
    60
  ).toString();
  const fromHour = `${nowMinus.getHours()}:${closestQuarter.padStart(2, "0")}`;

  const eCO2mixNow = api.eco2mix.getForDateTime.useQuery({
    date: date as string,
    fromHour: fromHour,
  });

  const eCO2MixToday = api.eco2mix.getForDate.useQuery({
    date: date as string,
  });

  return (
    <>
      <Head>
        <title>WatWatt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>WatWatt</h1>
          <div className={styles.cardRow}></div>
          <div className={styles.showcaseContainer}>
            <Chart eCO2MixToday={eCO2MixToday?.data} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
